<?php

use App\Pais;
use Illuminate\Database\Seeder;

class paisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $pais = Pais::create(['codigo_pais'=>'13','nombre_pais'=>'AFGANISTAN']);
        $pais = Pais::create(['codigo_pais'=>'17','nombre_pais'=>'ALBANIA']);
        $pais = Pais::create(['codigo_pais'=>'23','nombre_pais'=>'ALEMANIA']);
        $pais = Pais::create(['codigo_pais'=>'26','nombre_pais'=>'ARMENIA']);
        $pais = Pais::create(['codigo_pais'=>'27','nombre_pais'=>'ARUBA']);
        $pais = Pais::create(['codigo_pais'=>'29','nombre_pais'=>'BOSNIA-HERZEGOVINA']);
        $pais = Pais::create(['codigo_pais'=>'31','nombre_pais'=>'BURKINA FASSO']);
        $pais = Pais::create(['codigo_pais'=>'37','nombre_pais'=>'ANDORRA']);
        $pais = Pais::create(['codigo_pais'=>'40','nombre_pais'=>'ANGOLA']);
        $pais = Pais::create(['codigo_pais'=>'41','nombre_pais'=>'ANGUILLA']);
        $pais = Pais::create(['codigo_pais'=>'43','nombre_pais'=>'ANTIGUA Y BARBUDA']);
        $pais = Pais::create(['codigo_pais'=>'47','nombre_pais'=>'ANTILLAS HOLANDESAS']);
        $pais = Pais::create(['codigo_pais'=>'53','nombre_pais'=>'ARABIA SAUDITA']);
        $pais = Pais::create(['codigo_pais'=>'59','nombre_pais'=>'ARGELIA']);
        $pais = Pais::create(['codigo_pais'=>'63','nombre_pais'=>'ARGENTINA']);
        $pais = Pais::create(['codigo_pais'=>'69','nombre_pais'=>'AUSTRALIA']);
        $pais = Pais::create(['codigo_pais'=>'72','nombre_pais'=>'AUSTRIA']);
        $pais = Pais::create(['codigo_pais'=>'74','nombre_pais'=>'AZERBAIJAN']);
        $pais = Pais::create(['codigo_pais'=>'77','nombre_pais'=>'BAHAMAS']);
        $pais = Pais::create(['codigo_pais'=>'80','nombre_pais'=>'BAHREIN']);
        $pais = Pais::create(['codigo_pais'=>'81','nombre_pais'=>'BANGLADESH']);
        $pais = Pais::create(['codigo_pais'=>'83','nombre_pais'=>'BARBADOS']);
        $pais = Pais::create(['codigo_pais'=>'87','nombre_pais'=>'BELGICA']);
        $pais = Pais::create(['codigo_pais'=>'88','nombre_pais'=>'BELICE']);
        $pais = Pais::create(['codigo_pais'=>'90','nombre_pais'=>'BERMUDAS']);
        $pais = Pais::create(['codigo_pais'=>'91','nombre_pais'=>'BELARUS']);
        $pais = Pais::create(['codigo_pais'=>'93','nombre_pais'=>'BIRMANIA MYANMAR']);
        $pais = Pais::create(['codigo_pais'=>'97','nombre_pais'=>'BOLIVIA']);
        $pais = Pais::create(['codigo_pais'=>'101','nombre_pais'=>'BOTSWANA']);
        $pais = Pais::create(['codigo_pais'=>'105','nombre_pais'=>'BRASIL']);
        $pais = Pais::create(['codigo_pais'=>'108','nombre_pais'=>'BRUNEI DARUSSALAM']);
        $pais = Pais::create(['codigo_pais'=>'111','nombre_pais'=>'BULGARIA']);
        $pais = Pais::create(['codigo_pais'=>'115','nombre_pais'=>'BURUNDI']);
        $pais = Pais::create(['codigo_pais'=>'119','nombre_pais'=>'BUTAN']);
        $pais = Pais::create(['codigo_pais'=>'127','nombre_pais'=>'CABO VERDE']);
        $pais = Pais::create(['codigo_pais'=>'137','nombre_pais'=>'CAIMAN ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'141','nombre_pais'=>'CAMBOYA KAMPUCHEA']);
        $pais = Pais::create(['codigo_pais'=>'145','nombre_pais'=>'CAMERUN REPUBLICA UNIDA DEL']);
        $pais = Pais::create(['codigo_pais'=>'149','nombre_pais'=>'CANADA']);
        $pais = Pais::create(['codigo_pais'=>'159','nombre_pais'=>'SANTA SEDE']);
        $pais = Pais::create(['codigo_pais'=>'165','nombre_pais'=>'COCOS KEELING ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'169','nombre_pais'=>'COLOMBIA']);
        $pais = Pais::create(['codigo_pais'=>'173','nombre_pais'=>'COMORAS']);
        $pais = Pais::create(['codigo_pais'=>'177','nombre_pais'=>'CONGO']);
        $pais = Pais::create(['codigo_pais'=>'183','nombre_pais'=>'COOK ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'187','nombre_pais'=>'COREA NORTE  REPUBLICA POPULAR DEMOCRATICA DE']);
        $pais = Pais::create(['codigo_pais'=>'190','nombre_pais'=>'COREA SUR REPUBLICA DE']);
        $pais = Pais::create(['codigo_pais'=>'193','nombre_pais'=>'COSTA DE MARFIL']);
        $pais = Pais::create(['codigo_pais'=>'196','nombre_pais'=>'COSTA RICA']);
        $pais = Pais::create(['codigo_pais'=>'198','nombre_pais'=>'CROACIA']);
        $pais = Pais::create(['codigo_pais'=>'199','nombre_pais'=>'CUBA']);
        $pais = Pais::create(['codigo_pais'=>'203','nombre_pais'=>'CHAD']);
        $pais = Pais::create(['codigo_pais'=>'211','nombre_pais'=>'CHILE']);
        $pais = Pais::create(['codigo_pais'=>'215','nombre_pais'=>'CHINA']);
        $pais = Pais::create(['codigo_pais'=>'218','nombre_pais'=>'TAIWAN FORMOSA']);
        $pais = Pais::create(['codigo_pais'=>'221','nombre_pais'=>'CHIPRE']);
        $pais = Pais::create(['codigo_pais'=>'229','nombre_pais'=>'BENIN']);
        $pais = Pais::create(['codigo_pais'=>'232','nombre_pais'=>'DINAMARCA']);
        $pais = Pais::create(['codigo_pais'=>'235','nombre_pais'=>'DOMINICA']);
        $pais = Pais::create(['codigo_pais'=>'239','nombre_pais'=>'ECUADOR']);
        $pais = Pais::create(['codigo_pais'=>'240','nombre_pais'=>'EGIPTO']);
        $pais = Pais::create(['codigo_pais'=>'242','nombre_pais'=>'EL SALVADOR']);
        $pais = Pais::create(['codigo_pais'=>'243','nombre_pais'=>'ERITREA']);
        $pais = Pais::create(['codigo_pais'=>'244','nombre_pais'=>'EMIRATOS ARABES UNIDOS']);
        $pais = Pais::create(['codigo_pais'=>'245','nombre_pais'=>'ESPA?A']);
        $pais = Pais::create(['codigo_pais'=>'246','nombre_pais'=>'ESLOVAQUIA']);
        $pais = Pais::create(['codigo_pais'=>'247','nombre_pais'=>'ESLOVENIA']);
        $pais = Pais::create(['codigo_pais'=>'249','nombre_pais'=>'ESTADOS UNIDOS']);
        $pais = Pais::create(['codigo_pais'=>'251','nombre_pais'=>'ESTONIA']);
        $pais = Pais::create(['codigo_pais'=>'253','nombre_pais'=>'ETIOPIA']);
        $pais = Pais::create(['codigo_pais'=>'259','nombre_pais'=>'FEROE ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'267','nombre_pais'=>'FILIPINAS']);
        $pais = Pais::create(['codigo_pais'=>'271','nombre_pais'=>'FINLANDIA']);
        $pais = Pais::create(['codigo_pais'=>'275','nombre_pais'=>'FRANCIA']);
        $pais = Pais::create(['codigo_pais'=>'281','nombre_pais'=>'GABON']);
        $pais = Pais::create(['codigo_pais'=>'285','nombre_pais'=>'GAMBIA']);
        $pais = Pais::create(['codigo_pais'=>'287','nombre_pais'=>'GEORGIA']);
        $pais = Pais::create(['codigo_pais'=>'289','nombre_pais'=>'GHANA']);
        $pais = Pais::create(['codigo_pais'=>'293','nombre_pais'=>'GIBRALTAR']);
        $pais = Pais::create(['codigo_pais'=>'297','nombre_pais'=>'GRANADA']);
        $pais = Pais::create(['codigo_pais'=>'301','nombre_pais'=>'GRECIA']);
        $pais = Pais::create(['codigo_pais'=>'305','nombre_pais'=>'GROENLANDIA']);
        $pais = Pais::create(['codigo_pais'=>'309','nombre_pais'=>'GUADALUPE']);
        $pais = Pais::create(['codigo_pais'=>'313','nombre_pais'=>'GUAM']);
        $pais = Pais::create(['codigo_pais'=>'317','nombre_pais'=>'GUATEMALA']);
        $pais = Pais::create(['codigo_pais'=>'325','nombre_pais'=>'GUAYANA FRANCESA']);
        $pais = Pais::create(['codigo_pais'=>'329','nombre_pais'=>'GUINEA']);
        $pais = Pais::create(['codigo_pais'=>'331','nombre_pais'=>'GUINEA ECUATORIAL']);
        $pais = Pais::create(['codigo_pais'=>'334','nombre_pais'=>'GUINEA-BISSAU']);
        $pais = Pais::create(['codigo_pais'=>'337','nombre_pais'=>'GUAYANA']);
        $pais = Pais::create(['codigo_pais'=>'341','nombre_pais'=>'HAITI']);
        $pais = Pais::create(['codigo_pais'=>'345','nombre_pais'=>'HONDURAS']);
        $pais = Pais::create(['codigo_pais'=>'351','nombre_pais'=>'HONG KONG']);
        $pais = Pais::create(['codigo_pais'=>'355','nombre_pais'=>'HUNGRIA']);
        $pais = Pais::create(['codigo_pais'=>'361','nombre_pais'=>'INDIA']);
        $pais = Pais::create(['codigo_pais'=>'365','nombre_pais'=>'INDONESIA']);
        $pais = Pais::create(['codigo_pais'=>'369','nombre_pais'=>'IRAK']);
        $pais = Pais::create(['codigo_pais'=>'372','nombre_pais'=>'IRAN REPUBLICA ISLAMICA DEL']);
        $pais = Pais::create(['codigo_pais'=>'375','nombre_pais'=>'IRLANDA EIRE']);
        $pais = Pais::create(['codigo_pais'=>'379','nombre_pais'=>'ISLANDIA']);
        $pais = Pais::create(['codigo_pais'=>'383','nombre_pais'=>'ISRAEL']);
        $pais = Pais::create(['codigo_pais'=>'386','nombre_pais'=>'ITALIA']);
        $pais = Pais::create(['codigo_pais'=>'391','nombre_pais'=>'JAMAICA']);
        $pais = Pais::create(['codigo_pais'=>'399','nombre_pais'=>'JAPON']);
        $pais = Pais::create(['codigo_pais'=>'403','nombre_pais'=>'JORDANIA']);
        $pais = Pais::create(['codigo_pais'=>'406','nombre_pais'=>'KASAJSTAN']);
        $pais = Pais::create(['codigo_pais'=>'410','nombre_pais'=>'KENIA']);
        $pais = Pais::create(['codigo_pais'=>'411','nombre_pais'=>'KIRIBATI']);
        $pais = Pais::create(['codigo_pais'=>'412','nombre_pais'=>'KIRGUIZISTAN']);
        $pais = Pais::create(['codigo_pais'=>'413','nombre_pais'=>'KUWAIT']);
        $pais = Pais::create(['codigo_pais'=>'420','nombre_pais'=>'LAOS REPUBLICA POPULAR DEMOCRATICA DE']);
        $pais = Pais::create(['codigo_pais'=>'426','nombre_pais'=>'LESOTHO']);
        $pais = Pais::create(['codigo_pais'=>'429','nombre_pais'=>'LETONIA']);
        $pais = Pais::create(['codigo_pais'=>'431','nombre_pais'=>'LIBANO']);
        $pais = Pais::create(['codigo_pais'=>'434','nombre_pais'=>'LIBERIA']);
        $pais = Pais::create(['codigo_pais'=>'438','nombre_pais'=>'LIBIA INCLUYE FEZZAN']);
        $pais = Pais::create(['codigo_pais'=>'440','nombre_pais'=>'LIECHTENSTEIN']);
        $pais = Pais::create(['codigo_pais'=>'443','nombre_pais'=>'LITUANIA']);
        $pais = Pais::create(['codigo_pais'=>'445','nombre_pais'=>'LUXEMBURGO']);
        $pais = Pais::create(['codigo_pais'=>'447','nombre_pais'=>'MACAO']);
        $pais = Pais::create(['codigo_pais'=>'448','nombre_pais'=>'MACEDONIA']);
        $pais = Pais::create(['codigo_pais'=>'450','nombre_pais'=>'MADAGASCAR']);
        $pais = Pais::create(['codigo_pais'=>'455','nombre_pais'=>'MALAYSIA']);
        $pais = Pais::create(['codigo_pais'=>'458','nombre_pais'=>'MALAWI']);
        $pais = Pais::create(['codigo_pais'=>'461','nombre_pais'=>'MALDIVAS']);
        $pais = Pais::create(['codigo_pais'=>'464','nombre_pais'=>'MALI']);
        $pais = Pais::create(['codigo_pais'=>'467','nombre_pais'=>'MALTA']);
        $pais = Pais::create(['codigo_pais'=>'469','nombre_pais'=>'MARIANAS DEL NORTE ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'472','nombre_pais'=>'MARSHALL ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'474','nombre_pais'=>'MARRUECOS']);
        $pais = Pais::create(['codigo_pais'=>'477','nombre_pais'=>'MARTINICA']);
        $pais = Pais::create(['codigo_pais'=>'485','nombre_pais'=>'MAURICIO']);
        $pais = Pais::create(['codigo_pais'=>'488','nombre_pais'=>'MAURITANIA']);
        $pais = Pais::create(['codigo_pais'=>'493','nombre_pais'=>'MEXICO']);
        $pais = Pais::create(['codigo_pais'=>'494','nombre_pais'=>'MICRONESIA ESTADOS FEDERADOS DE']);
        $pais = Pais::create(['codigo_pais'=>'496','nombre_pais'=>'MOLDAVIA']);
        $pais = Pais::create(['codigo_pais'=>'497','nombre_pais'=>'MONGOLIA']);
        $pais = Pais::create(['codigo_pais'=>'498','nombre_pais'=>'MONACO']);
        $pais = Pais::create(['codigo_pais'=>'501','nombre_pais'=>'MONSERRAT ISLA']);
        $pais = Pais::create(['codigo_pais'=>'505','nombre_pais'=>'MOZAMBIQUE']);
        $pais = Pais::create(['codigo_pais'=>'507','nombre_pais'=>'NAMIBIA']);
        $pais = Pais::create(['codigo_pais'=>'508','nombre_pais'=>'NAURU']);
        $pais = Pais::create(['codigo_pais'=>'511','nombre_pais'=>'NAVIDAD CHRISTMAS ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'517','nombre_pais'=>'NEPAL']);
        $pais = Pais::create(['codigo_pais'=>'521','nombre_pais'=>'NICARAGUA']);
        $pais = Pais::create(['codigo_pais'=>'525','nombre_pais'=>'NIGER']);
        $pais = Pais::create(['codigo_pais'=>'528','nombre_pais'=>'NIGERIA']);
        $pais = Pais::create(['codigo_pais'=>'531','nombre_pais'=>'NIUE ISLA']);
        $pais = Pais::create(['codigo_pais'=>'535','nombre_pais'=>'NORFOLK ISLA']);
        $pais = Pais::create(['codigo_pais'=>'538','nombre_pais'=>'NORUEGA']);
        $pais = Pais::create(['codigo_pais'=>'542','nombre_pais'=>'NUEVA CALEDONIA']);
        $pais = Pais::create(['codigo_pais'=>'545','nombre_pais'=>'PAPUASIA NUEVA GUINEA']);
        $pais = Pais::create(['codigo_pais'=>'548','nombre_pais'=>'NUEVA ZELANDIA']);
        $pais = Pais::create(['codigo_pais'=>'551','nombre_pais'=>'VANUATU']);
        $pais = Pais::create(['codigo_pais'=>'556','nombre_pais'=>'OMAN']);
        $pais = Pais::create(['codigo_pais'=>'566','nombre_pais'=>'PACIFICO ISLAS USA']);
        $pais = Pais::create(['codigo_pais'=>'573','nombre_pais'=>'Pais BAJOS HOLANDA']);
        $pais = Pais::create(['codigo_pais'=>'576','nombre_pais'=>'PAKISTAN']);
        $pais = Pais::create(['codigo_pais'=>'578','nombre_pais'=>'PALAU ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'580','nombre_pais'=>'PANAMA']);
        $pais = Pais::create(['codigo_pais'=>'586','nombre_pais'=>'PARAGUAY']);
        $pais = Pais::create(['codigo_pais'=>'589','nombre_pais'=>'PERU']);
        $pais = Pais::create(['codigo_pais'=>'593','nombre_pais'=>'PITCAIRN ISLA']);
        $pais = Pais::create(['codigo_pais'=>'599','nombre_pais'=>'POLINESIA FRANCESA']);
        $pais = Pais::create(['codigo_pais'=>'603','nombre_pais'=>'POLONIA']);
        $pais = Pais::create(['codigo_pais'=>'607','nombre_pais'=>'PORTUGAL']);
        $pais = Pais::create(['codigo_pais'=>'611','nombre_pais'=>'PUERTO RICO']);
        $pais = Pais::create(['codigo_pais'=>'618','nombre_pais'=>'QATAR']);
        $pais = Pais::create(['codigo_pais'=>'628','nombre_pais'=>'REINO UNIDO']);
        $pais = Pais::create(['codigo_pais'=>'640','nombre_pais'=>'REPUBLICA CENTROAFRICANA']);
        $pais = Pais::create(['codigo_pais'=>'644','nombre_pais'=>'REPUBLICA CHECA']);
        $pais = Pais::create(['codigo_pais'=>'647','nombre_pais'=>'REPUBLICA DOMINICANA']);
        $pais = Pais::create(['codigo_pais'=>'660','nombre_pais'=>'REUNION']);
        $pais = Pais::create(['codigo_pais'=>'665','nombre_pais'=>'ZIMBABWE']);
        $pais = Pais::create(['codigo_pais'=>'670','nombre_pais'=>'RUMANIA']);
        $pais = Pais::create(['codigo_pais'=>'675','nombre_pais'=>'RUANDA']);
        $pais = Pais::create(['codigo_pais'=>'676','nombre_pais'=>'RUSIA']);
        $pais = Pais::create(['codigo_pais'=>'677','nombre_pais'=>'SALOMON ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'685','nombre_pais'=>'SAHARA OCCIDENTAL']);
        $pais = Pais::create(['codigo_pais'=>'687','nombre_pais'=>'SAMOA']);
        $pais = Pais::create(['codigo_pais'=>'690','nombre_pais'=>'SAMOA NORTEAMERICANA']);
        $pais = Pais::create(['codigo_pais'=>'695','nombre_pais'=>'SAN CRISTOBAL Y NIEVES']);
        $pais = Pais::create(['codigo_pais'=>'697','nombre_pais'=>'SAN MARINO']);
        $pais = Pais::create(['codigo_pais'=>'700','nombre_pais'=>'SAN PEDRO Y MIGUELON']);
        $pais = Pais::create(['codigo_pais'=>'705','nombre_pais'=>'SAN VICENTE Y LAS GRANADINAS']);
        $pais = Pais::create(['codigo_pais'=>'710','nombre_pais'=>'SANTA ELENA']);
        $pais = Pais::create(['codigo_pais'=>'715','nombre_pais'=>'SANTA LUCIA']);
        $pais = Pais::create(['codigo_pais'=>'720','nombre_pais'=>'SANTO TOME Y PRINCIPE']);
        $pais = Pais::create(['codigo_pais'=>'728','nombre_pais'=>'SENEGAL']);
        $pais = Pais::create(['codigo_pais'=>'731','nombre_pais'=>'SEYCHELLES']);
        $pais = Pais::create(['codigo_pais'=>'735','nombre_pais'=>'SIERRA LEONA']);
        $pais = Pais::create(['codigo_pais'=>'741','nombre_pais'=>'SINGAPUR']);
        $pais = Pais::create(['codigo_pais'=>'744','nombre_pais'=>'SIRIA  REPUBLICA ARABE DE']);
        $pais = Pais::create(['codigo_pais'=>'748','nombre_pais'=>'SOMALIA']);
        $pais = Pais::create(['codigo_pais'=>'750','nombre_pais'=>'SRI LANKA']);
        $pais = Pais::create(['codigo_pais'=>'756','nombre_pais'=>'SUDAFRICA REPUBLICA DE']);
        $pais = Pais::create(['codigo_pais'=>'759','nombre_pais'=>'SUDAN']);
        $pais = Pais::create(['codigo_pais'=>'764','nombre_pais'=>'SUECIA']);
        $pais = Pais::create(['codigo_pais'=>'767','nombre_pais'=>'SUIZA']);
        $pais = Pais::create(['codigo_pais'=>'770','nombre_pais'=>'SURINAM']);
        $pais = Pais::create(['codigo_pais'=>'773','nombre_pais'=>'SWAZILANDIA']);
        $pais = Pais::create(['codigo_pais'=>'774','nombre_pais'=>'TADJIKISTAN']);
        $pais = Pais::create(['codigo_pais'=>'776','nombre_pais'=>'TAILANDIA']);
        $pais = Pais::create(['codigo_pais'=>'780','nombre_pais'=>'TANZANIA REPUBLICA UNIDA DE']);
        $pais = Pais::create(['codigo_pais'=>'783','nombre_pais'=>'DJIBOUTI']);
        $pais = Pais::create(['codigo_pais'=>'787','nombre_pais'=>'TERRITORIO BRITANICO DEL OCEANO INDICO']);
        $pais = Pais::create(['codigo_pais'=>'788','nombre_pais'=>'TIMOR DEL ESTE']);
        $pais = Pais::create(['codigo_pais'=>'800','nombre_pais'=>'TOGO']);
        $pais = Pais::create(['codigo_pais'=>'805','nombre_pais'=>'TOKELAU']);
        $pais = Pais::create(['codigo_pais'=>'810','nombre_pais'=>'TONGA']);
        $pais = Pais::create(['codigo_pais'=>'815','nombre_pais'=>'TRINIDAD Y TOBAGO']);
        $pais = Pais::create(['codigo_pais'=>'820','nombre_pais'=>'TUNICIA']);
        $pais = Pais::create(['codigo_pais'=>'823','nombre_pais'=>'TURCAS Y CAICOS ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'825','nombre_pais'=>'TURKMENISTAN']);
        $pais = Pais::create(['codigo_pais'=>'827','nombre_pais'=>'TURQUIA']);
        $pais = Pais::create(['codigo_pais'=>'828','nombre_pais'=>'TUVALU']);
        $pais = Pais::create(['codigo_pais'=>'830','nombre_pais'=>'UCRANIA']);
        $pais = Pais::create(['codigo_pais'=>'833','nombre_pais'=>'UGANDA']);
        $pais = Pais::create(['codigo_pais'=>'845','nombre_pais'=>'URUGUAY']);
        $pais = Pais::create(['codigo_pais'=>'847','nombre_pais'=>'UZBEKISTAN']);
        $pais = Pais::create(['codigo_pais'=>'850','nombre_pais'=>'VENEZUELA']);
        $pais = Pais::create(['codigo_pais'=>'855','nombre_pais'=>'VIET NAM']);
        $pais = Pais::create(['codigo_pais'=>'863','nombre_pais'=>'VIRGENES ISLAS BRITANICAS']);
        $pais = Pais::create(['codigo_pais'=>'866','nombre_pais'=>'VIRGENES ISLAS NORTEAMERICANAS']);
        $pais = Pais::create(['codigo_pais'=>'870','nombre_pais'=>'FIJI']);
        $pais = Pais::create(['codigo_pais'=>'875','nombre_pais'=>'WALLIS Y FORTUNA ISLAS']);
        $pais = Pais::create(['codigo_pais'=>'880','nombre_pais'=>'YEMEN']);
        $pais = Pais::create(['codigo_pais'=>'885','nombre_pais'=>'YUGOSLAVIA']);
        $pais = Pais::create(['codigo_pais'=>'888','nombre_pais'=>'ZAIRE']);
        $pais = Pais::create(['codigo_pais'=>'890','nombre_pais'=>'ZAMBIA']);
        $pais = Pais::create(['codigo_pais'=>'897','nombre_pais'=>'ZONA NEUTRAL PALESTINA']);
    }
}
